### PR TITLE
Fix typos in the Windows download page

### PR DESCRIPTION
**Pull request by guihkx**

### CODE REVIEW

**Comment by phoerious** [comment]
This is not a typo. The MSI file is an "Installer" that installs KeePassXC.

**Comment by guihkx** [comment]
I'm sorry, english isn't my native language. I thought it was supposed to be "installer" and not "installed" here:

image

But thanks for clarifying!

**Comment by droidmonkey** [comment]
That certainly is a typo

**Comment by phoerious** [comment]
You're right. I misread your patch. I thought you wanted to replace "Installer" with "Installed".

Thanks!

**Comment by guihkx** [comment]
No worries!

**Pull request merged**
