### PR TITLE
Add Yubikey 2FA support to the features list

### PR DESCRIPTION
**Pull request by stmllr**
Streamline the features list with the projects README.

### CODE REVIEW

**Comment by phoerious** [comment]
This should be called "YukiKey HMAC-SHA1 authentication" and not "Yubikey 2FA".

**Comment by phoerious** [comment]
We should change that in the README as well. I'll defer merging this, though, until 2.2.0 is out.

**Comment by stmllr** [comment]
@phoerious see https://github.com/keepassxreboot/keepassxc/pull/395

**Comment by phoerious** [comment]
You should replace YukiKey with YubiKey. ;-)

**Comment by stmllr** [comment]
copy paste blindness. fixed

**Pull request merged**
