### PR TITLE
Add Chocolatey download source

### PR DESCRIPTION
**Pull request by karlhorky**
Hi there, thanks for this project!

Just a quick PR to add [the Chocolatey package](https://chocolatey.org/packages/keepassxc) as a download source for Windows (similar to Homebrew on macOS).

### CODE REVIEW

**Comment by phoerious** [comment]
May I ask for supplemental changes? The layout is slightly broken with missing margins, because the row and dist-packages classes are set on the same element instead of separate nested elements. Please correct them to resemble what the Linux download tab has.

**Comment by droidmonkey** [comment]
Hmmmm i tested locally and copy/pasted from the linux side. Must have screwed it up somehow

**Comment by karlhorky** [comment]
Should I do another PR for this?

**Comment by karlhorky** [comment]
Opened #55 for this. cc @phoerious @droidmonkey

**Pull request merged**
