### PR TITLE
Improve resolution and compatibility of favicon

### PR DESCRIPTION
**Pull request by karlhorky**
Improve the resolution of and compatibility of the favicon, which is currently quite small and blurry:

Screen Shot 2019-04-04 at 16 16 16

Based on files generated by [RealFaviconGenerator](https://realfavicongenerator.net) and other tools:

[favicon_package_v0.16-edit.zip](https://github.com/keepassxreboot/keepassxreboot.github.io/files/3043962/favicon_package_v0.16-edit.zip)

### CODE REVIEW

**Comment by droidmonkey** [comment]
Is it intended for the apple touch icon to have a white background instead of transparent?

**Comment by karlhorky** [comment]
Yep, intended. The icon will appear in a rounded rectangle with a white background on iOS.

**Comment by karlhorky** [comment]
@droidmonkey Looks like this broke the favicon.

Screen Shot 2019-04-05 at 15 54 43

Weirdly enough if I try accessing the new files, they are redirected with a slash at the end.

Screen Shot 2019-04-05 at 15 54 35
Screen Shot 2019-04-05 at 15 54 39

It seems like there's a rewrite in the `.htaccess` that is putting slashes at the end of requests, could that be the problem?

https://github.com/keepassxreboot/keepassxreboot.github.io/blob/0f6a30379757e779c96ff23256909454beba56bd/.htaccess#L18

**Comment by karlhorky** [comment]
But if this is just served by GitHub Pages, I suppose `.htaccess` doesn't actually get used...

**Comment by karlhorky** [comment]
Hm, just tried with Jekyll on my machine locally and it's serving the images correctly:

Screen Shot 2019-04-05 at 16 17 28

**Comment by droidmonkey** [comment]
Yah it worked locally for me as well

**Comment by karlhorky** [comment]
Maybe it was 0f6a30379757e779c96ff23256909454beba56bd that introduced this issue?

**Comment by droidmonkey** [comment]
No, for some reason the image files added by this PR are not showing up on the server. They are legit missing. I am trying to reactivate the git hook.

**Comment by droidmonkey** [comment]
OK they are up now. For some reason the jekyll build failed.

**Comment by phoerious** [comment]
The website is not served by Github pages and the RewriteCond disables the slash redirect for exiting files.

**Pull request merged**
