### PR TITLE
Add missing download sources(as per #28)

### PR DESCRIPTION
**Pull request by pshem**
I know reducing the width of BSD and macOS is a horrible idea, but I don't have a better one - the sum needs to be 12. MacOS this way, it's symmetrical and both 2 length OSs have short names.

### CODE REVIEW

**Comment by phoerious** [comment]
The Flatpak package is not maintained by us and therefore doesn't belong with the other official listings. Neither is the BSD package. We can list them under "Distribution Packages".

**Comment by TheZ3ro** [comment]
@phoerious but also the Homebrew Cask isn't maintained by us but it's still there. Should we remove it as well?
After all they are pulling source from the original repo and compiling it on user's PC, they are not releasing binary packages.

**Comment by phoerious** [comment]
Homebrew is different in the sense that it's just pulling the original DMG without modifications. Flatpaks are wrapping KeePassXC into containers, which can cause issues we have no control over (there are bug reports already).

**Comment by pshem** [comment]
I've done this properly now. Sorry for the number of commits, I tried being lazy and doing it through github instead of git - that was a bad idea:

1. I implemented the offset as @TheZ3ro wanted, with 1 empty column on each side. Is there a way to see the website preview for the current branch? I'm not keen on installing ruby tbh.

2. MacPorts and Homebrew are now marked as distribution packages... but given @phoerious  comment, I might have to reverse it ;)

3. Which link to the flatpak should I use? The one to the github repository, or the one to the flatpakref? I've put the repository as a comment in the source code for now. I could also have it show both links, the way Windows downloads do. That's the strategy I went for with MacPorts.

4. Should Portable apps be listed as a Distribution package? If I remember correctly, they only add a package manager on top of the portable version. I've not changed the Windows tab yet.

**Comment by phoerious** [comment]
We have staging.keepassxc.org, which builds from develop, but without merging the branch first, there is no way to preview the changes without compiling it with jekyll.

**Comment by droidmonkey** [comment]
Closing this.

**Pull request closed without merging**
