### PR TITLE
Add SSH agent FAQ entry: I'm getting a "Too many authentication failures" error, what shall I do?

### PR DESCRIPTION
**Pull request by PhrozenByte**
> I'm getting a "Too many authentication failures" error, what shall I do?

### CODE REVIEW

**Comment by PhrozenByte** [comment]
Any updates here?

**Comment by droidmonkey** [comment]
Maybe a little description about your motivation for this pull request please

**Comment by PhrozenByte** [comment]
Had this issue and this is the solution and this behaviour/feature of KeePassXC is currently undocumented.

**Comment by droidmonkey** [comment]
Thank you for the addition!

**Pull request merged**
