### PR TITLE
add Windows Package Manager Package

### PR DESCRIPTION
**Pull request by trockenasche**
Add Windows Package Manager information at the Windows download page.

### CODE REVIEW

**Comment by trockenasche** [comment]
Would you mind to add _hacktoberfest_ tag to the repo? It's okay if you don't.

**Comment by droidmonkey** [comment]
What is this all about?

**Comment by trockenasche** [comment]
I just added a second "3rd-Party Distribution" for windows.
Winget is the Microsoft alternative to Chocolatey.

**Comment by droidmonkey** [comment]
Why is it listed under KeePassXCTeam? Clearly we, the KeePassXC Team, did not create that.

**Comment by trockenasche** [comment]
I don't know, it was already at the winget repo.

**Comment by droidmonkey** [comment]
Gotcha thank you

**Review by droidmonkey — APPROVED** [review]

**Pull request merged**
